target_include_directories(
    gpu-mwdg2
    PRIVATE
    source/classes
    source/input
    source/mra
    source/neighbours
    source/operators
    source/output
    source/tests
    source/types
    source/utilities
    source/zorder
)